/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cpscanner_algorithm_MathAlgs */

#ifndef _Included_com_cpscanner_algorithm_MathAlgs
#define _Included_com_cpscanner_algorithm_MathAlgs
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cpscanner_algorithm_MathAlgs
 * Method:    solveTriangle
 * Signature: ([D)V
 */
JNIEXPORT void JNICALL Java_com_cpscanner_algorithm_MathAlgs_solveTriangle
  (JNIEnv *, jclass, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
