/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cp_scanner_algo_StringAlgs */

#ifndef _Included_cp_scanner_algo_StringAlgs
#define _Included_cp_scanner_algo_StringAlgs
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cp_scanner_algo_StringAlgs
 * Method:    arithmancy
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_cp_scanner_algo_StringAlgs_arithmancy
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
