/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_scanner_main_OtherMethods */

#ifndef _Included_com_scanner_main_OtherMethods
#define _Included_com_scanner_main_OtherMethods
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_scanner_main_OtherMethods
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_scanner_main_OtherMethods_init
  (JNIEnv *, jclass);

/*
 * Class:     com_scanner_main_OtherMethods
 * Method:    permute
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_scanner_main_OtherMethods_permute
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_scanner_main_OtherMethods
 * Method:    flushbuf
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_scanner_main_OtherMethods_flushbuf
  (JNIEnv *, jclass);

/*
 * Class:     com_scanner_main_OtherMethods
 * Method:    logdat
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_scanner_main_OtherMethods_logdat
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_scanner_main_OtherMethods
 * Method:    setAutoRole
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_scanner_main_OtherMethods_setAutoRole
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_scanner_main_OtherMethods
 * Method:    getAutoRole
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_scanner_main_OtherMethods_getAutoRole
  (JNIEnv *, jclass);

/*
 * Class:     com_scanner_main_OtherMethods
 * Method:    nextSelfRole
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_scanner_main_OtherMethods_nextSelfRole
  (JNIEnv *, jclass);

/*
 * Class:     com_scanner_main_OtherMethods
 * Method:    changeSelfRole
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_scanner_main_OtherMethods_changeSelfRole
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_scanner_main_OtherMethods
 * Method:    testSelfRole
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_scanner_main_OtherMethods_testSelfRole
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_scanner_main_OtherMethods
 * Method:    work
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_scanner_main_OtherMethods_work
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_scanner_main_OtherMethods
 * Method:    crime
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_scanner_main_OtherMethods_crime
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_scanner_main_OtherMethods
 * Method:    fight
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_scanner_main_OtherMethods_fight
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
