/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_scanner_main_MathMethods */

#ifndef _Included_com_scanner_main_MathMethods
#define _Included_com_scanner_main_MathMethods
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_scanner_main_MathMethods
 * Method:    plog
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_com_scanner_main_MathMethods_plog
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     com_scanner_main_MathMethods
 * Method:    fact
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_com_scanner_main_MathMethods_fact
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     com_scanner_main_MathMethods
 * Method:    fndpoi
 * Signature: (DDDDDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_scanner_main_MathMethods_fndpoi
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     com_scanner_main_MathMethods
 * Method:    median
 * Signature: ([D)D
 */
JNIEXPORT jdouble JNICALL Java_com_scanner_main_MathMethods_median
  (JNIEnv *, jclass, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
